export const TYPES = {
    AuthRepository: Symbol.for("AuthRepository"),
    AuthService: Symbol.for("AuthService"),
    AuthController: Symbol.for("AuthController"),
    TmdbService: Symbol.for("TmdbService"),
    TmdbCacheService: Symbol.for("TmdbCacheService"),
    TmdbController: Symbol.for("TmdbController"),
    TrackingService: Symbol.for("TrackingService"),
    TrackingController: Symbol.for("TrackingController"),
    ListRepository: Symbol.for("ListRepository"),
    ListService: Symbol.for("ListService"),
    ListController: Symbol.for("ListController"),
    UserRepository: Symbol.for("UserRepository"),
    UserService: Symbol.for("UserService"),
    UserCategorizationService: Symbol.for("UserCategorizationService"),
    UserController: Symbol.for("UserController"),
    OmdbCacheRepository: Symbol.for("OmdbCacheRepository"),
    TmdbCacheRepository: Symbol.for("TmdbCacheRepository"),
};
